import { ChampionData } from "../types";

export const JUNGLE_CHAMPIONS: ChampionData[] = [
  { name: "Aatrox", loses: 2, funNote: 5, commentary: "", completed: !false },
  { name: "Ambessa", loses: 2, funNote: 0, commentary: "", completed: false },
  { name: "Amumu", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Brand", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Briar", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Chogath", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Darius", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Diana", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "DrMundo", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Ekko", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Elise", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Evelynn", loses: 0, funNote: 0, commentary: "", completed: false },
  {
    name: "Fiddlesticks",
    loses: 0,
    funNote: 0,
    commentary: "",
    completed: false,
  },
  { name: "Gragas", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Graves", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Hecarim", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Ivern", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "JarvanIV", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Jax", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Jayce", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Karthus", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Kayn", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Khazix", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Kindred", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "LeeSin", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Lillia", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Locke", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Malphite", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Maokai", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "MasterYi", loses: 0, funNote: 0, commentary: "", completed: false },
  {
    name: "Mordekaiser",
    loses: 0,
    funNote: 0,
    commentary: "",
    completed: false,
  },
  { name: "Morgana", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Naafiri", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Nasus", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Nidalee", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Nocturne", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Nunu", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Olaf", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Pantheon", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Poppy", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Quinn", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Rammus", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "RekSai", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Rengar", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Sejuani", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Shaco", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Shyvana", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Skarner", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Sylas", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Talon", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Trundle", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Udyr", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Vi", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Viego", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Volibear", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Warwick", loses: 0, funNote: 0, commentary: "", completed: false },
  {
    name: "MonkeyKing",
    loses: 0,
    funNote: 0,
    commentary: "",
    completed: false,
  },
  { name: "XinZhao", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Zaahen", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Zac", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Zed", loses: 0, funNote: 0, commentary: "", completed: false },
  { name: "Zyra", loses: 0, funNote: 0, commentary: "", completed: false },
];
