import { createChampion } from "./utils/createChampion";
import { createChampionData } from "./utils/createChampionData";

const JUNGLE_CHAMPIONS = [
  createChampion("aatrox", "Aatrox", "Aatrox"),
  createChampion("ambessa", "Ambessa", "Ambessa"),
  createChampion("amumu", "Amumu", "Amumu"),
  createChampion("brand", "Brand", "Brand"),
  createChampion("briar", "Briar", "Briar"),
  createChampion("chogath", "Chogath", "Cho'Gath"),
  createChampion("darius", "Darius", "Darius"),
  createChampion("diana", "Diana", "Diana"),
  createChampion("drmundo", "DrMundo", "Dr. Mundo"),
  createChampion("ekko", "Ekko", "Ekko"),
  createChampion("elise", "Elise", "Elise"),
  createChampion("evelynn", "Evelynn", "Evelynn"),
  createChampion("fiddlesticks", "Fiddlesticks", "Fiddlesticks"),
  createChampion("gragas", "Gragas", "Gragas"),
  createChampion("graves", "Graves", "Graves"),
  createChampion("hecarim", "Hecarim", "Hecarim"),
  createChampion("ivern", "Ivern", "Ivern"),
  createChampion("jarvaniv", "JarvanIV", "Jarvan IV"),
  createChampion("jax", "Jax", "Jax"),
  createChampion("jayce", "Jayce", "Jayce"),
  createChampion("karthus", "Karthus", "Karthus"),
  createChampion("kayn", "Kayn", "Kayn"),
  createChampion("khazix", "Khazix", "Kha'Zix"),
  createChampion("kindred", "Kindred", "Kindred"),
  createChampion("leesin", "LeeSin", "Lee Sin"),
  createChampion("lillia", "Lillia", "Lillia"),
  createChampion("locke", "Locke", "Locke"),
  createChampion("malphite", "Malphite", "Malphite"),
  createChampion("maokai", "Maokai", "Maokai"),
  createChampion("masteryi", "MasterYi", "Master Yi"),
  createChampion("mordekaiser", "Mordekaiser", "Mordekaiser"),
  createChampion("morgana", "Morgana", "Morgana"),
  createChampion("naafiri", "Naafiri", "Naafiri"),
  createChampion("nasus", "Nasus", "Nasus"),
  createChampion("nidalee", "Nidalee", "Nidalee"),
  createChampion("nocturne", "Nocturne", "Nocturne"),
  createChampion("nunu", "Nunu", "Nunu & Willump"),
  createChampion("olaf", "Olaf", "Olaf"),
  createChampion("pantheon", "Pantheon", "Pantheon"),
  createChampion("poppy", "Poppy", "Poppy"),
  createChampion("quinn", "Quinn", "Quinn"),
  createChampion("rammus", "Rammus", "Rammus"),
  createChampion("reksai", "RekSai", "Rek'Sai"),
  createChampion("rengar", "Rengar", "Rengar"),
  createChampion("sejuani", "Sejuani", "Sejuani"),
  createChampion("shaco", "Shaco", "Shaco"),
  createChampion("shyvana", "Shyvana", "Shyvana"),
  createChampion("skarner", "Skarner", "Skarner"),
  createChampion("sylas", "Sylas", "Sylas"),
  createChampion("talon", "Talon", "Talon"),
  createChampion("trundle", "Trundle", "Trundle"),
  createChampion("udyr", "Udyr", "Udyr"),
  createChampion("vi", "Vi", "Vi"),
  createChampion("viego", "Viego", "Viego"),
  createChampion("volibear", "Volibear", "Volibear"),
  createChampion("warwick", "Warwick", "Warwick"),
  createChampion("wukong", "MonkeyKing", "Wukong"),
  createChampion("xinzhao", "XinZhao", "Xin Zhao"),
  createChampion("zaahen", "Zaahen", "Zaahen"),
  createChampion("zac", "Zac", "Zac"),
  createChampion("zed", "Zed", "Zed"),
  createChampion("zyra", "Zyra", "Zyra"),
];

export const JUNGLE_CHAMPIONS_DATA = createChampionData(JUNGLE_CHAMPIONS);
