import { createChampion } from "./utils/createChampion";
import { createChampionData } from "./utils/createChampionData";

const MID_CHAMPIONS = [
  createChampion("ahri", "Ahri", "Ahri"),
  createChampion("akali", "Akali", "Akali"),
  createChampion("akshan", "Akshan", "Akshan"),
  createChampion("anivia", "Anivia", "Anivia"),
  createChampion("annie", "Annie", "Annie"),
  createChampion("aurelionsol", "AurelionSol", "Aurelion Sol"),
  createChampion("aurora", "Aurora", "Aurora"),
  createChampion("azir", "Azir", "Azir"),
  createChampion("brand", "Brand", "Brand"),
  createChampion("cassiopeia", "Cassiopeia", "Cassiopeia"),
  createChampion("corki", "Corki", "Corki"),
  createChampion("diana", "Diana", "Diana"),
  createChampion("ekko", "Ekko", "Ekko"),
  createChampion("fizz", "Fizz", "Fizz"),
  createChampion("galio", "Galio", "Galio"),
  createChampion("hwei", "Hwei", "Hwei"),
  createChampion("irelia", "Irelia", "Irelia"),
  createChampion("jayce", "Jayce", "Jayce"),
  createChampion("kassadin", "Kassadin", "Kassadin"),
  createChampion("katarina", "Katarina", "Katarina"),
  createChampion("leblanc", "Leblanc", "LeBlanc"),
  createChampion("lissandra", "Lissandra", "Lissandra"),
  createChampion("lucian", "Lucian", "Lucian"),
  createChampion("lux", "Lux", "Lux"),
  createChampion("malzahar", "Malzahar", "Malzahar"),
  createChampion("mel", "Mel", "Mel"),
  createChampion("naafiri", "Naafiri", "Naafiri"),
  createChampion("neeko", "Neeko", "Neeko"),
  createChampion("orianna", "Orianna", "Orianna"),
  createChampion("pantheon", "Pantheon", "Pantheon"),
  createChampion("qiyana", "Qiyana", "Qiyana"),
  createChampion("ryze", "Ryze", "Ryze"),
  createChampion("swain", "Swain", "Swain"),
  createChampion("sylas", "Sylas", "Sylas"),
  createChampion("syndra", "Syndra", "Syndra"),
  createChampion("talon", "Talon", "Talon"),
  createChampion("tristana", "Tristana", "Tristana"),
  createChampion("twistedfate", "TwistedFate", "Twisted Fate"),
  createChampion("veigar", "Veigar", "Veigar"),
  createChampion("velkoz", "Velkoz", "Vel'Koz"),
  createChampion("vex", "Vex", "Vex"),
  createChampion("viktor", "Viktor", "Viktor"),
  createChampion("vladimir", "Vladimir", "Vladimir"),
  createChampion("xerath", "Xerath", "Xerath"),
  createChampion("yasuo", "Yasuo", "Yasuo"),
  createChampion("yone", "Yone", "Yone"),
  createChampion("zed", "Zed", "Zed"),
  createChampion("ziggs", "Ziggs", "Ziggs"),
  createChampion("zoe", "Zoe", "Zoe"),
];

export const MID_CHAMPIONS_DATA = createChampionData(MID_CHAMPIONS);
