import { createChampion } from "./utils/createChampion";
import { createChampionData } from "./utils/createChampionData";

const TOP_CHAMPIONS = [
  createChampion("aatrox", "Aatrox", "Aatrox"),
  createChampion("akali", "Akali", "Akali"),
  createChampion("ambessa", "Ambessa", "Ambessa"),
  createChampion("aurora", "Aurora", "Aurora"),
  createChampion("camille", "Camille", "Camille"),
  createChampion("cassiopeia", "Cassiopeia", "Cassiopeia"),
  createChampion("chogath", "Chogath", "Cho'Gath"),
  createChampion("darius", "Darius", "Darius"),
  createChampion("drmundo", "DrMundo", "Dr. Mundo"),
  createChampion("fiora", "Fiora", "Fiora"),
  createChampion("gangplank", "Gangplank", "Gangplank"),
  createChampion("garen", "Garen", "Garen"),
  createChampion("gnar", "Gnar", "Gnar"),
  createChampion("gragas", "Gragas", "Gragas"),
  createChampion("gwen", "Gwen", "Gwen"),
  createChampion("illaoi", "Illaoi", "Illaoi"),
  createChampion("irelia", "Irelia", "Irelia"),
  createChampion("jax", "Jax", "Jax"),
  createChampion("jayce", "Jayce", "Jayce"),
  createChampion("ksante", "KSante", "K'Sante"),
  createChampion("kayle", "Kayle", "Kayle"),
  createChampion("kennen", "Kennen", "Kennen"),
  createChampion("kled", "Kled", "Kled"),
  createChampion("malphite", "Malphite", "Malphite"),
  createChampion("maokai", "Maokai", "Maokai"),
  createChampion("mordekaiser", "Mordekaiser", "Mordekaiser"),
  createChampion("nasus", "Nasus", "Nasus"),
  createChampion("olaf", "Olaf", "Olaf"),
  createChampion("ornn", "Ornn", "Ornn"),
  createChampion("pantheon", "Pantheon", "Pantheon"),
  createChampion("poppy", "Poppy", "Poppy"),
  createChampion("quinn", "Quinn", "Quinn"),
  createChampion("renekton", "Renekton", "Renekton"),
  createChampion("riven", "Riven", "Riven"),
  createChampion("rumble", "Rumble", "Rumble"),
  createChampion("sett", "Sett", "Sett"),
  createChampion("shen", "Shen", "Shen"),
  createChampion("singed", "Singed", "Singed"),
  createChampion("sion", "Sion", "Sion"),
  createChampion("teemo", "Teemo", "Teemo"),
  createChampion("trundle", "Trundle", "Trundle"),
  createChampion("tryndamere", "Tryndamere", "Tryndamere"),
  createChampion("urgot", "Urgot", "Urgot"),
  createChampion("vayne", "Vayne", "Vayne"),
  createChampion("volibear", "Volibear", "Volibear"),
  createChampion("warwick", "Warwick", "Warwick"),
  createChampion("wukong", "MonkeyKing", "Wukong"),
  createChampion("yasuo", "Yasuo", "Yasuo"),
  createChampion("yone", "Yone", "Yone"),
  createChampion("yorick", "Yorick", "Yorick"),
  createChampion("zac", "Zac", "Zac"),
];

export const TOP_CHAMPIONS_DATA = createChampionData(TOP_CHAMPIONS);
