import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import * as TooltipPrimitive from "@radix-ui/react-tooltip";

import Header from "@/src/components/layout/Header";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased bg-emerald-950 text-emerald-50`}
    >
      <TooltipPrimitive.Provider delayDuration={100}>
        <body className="min-h-full flex flex-col">
          <Header />
          <main>{children}</main>
        </body>
      </TooltipPrimitive.Provider>
    </html>
  );
}
